name: Android Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17' # Use the Java version compatible with your Android project

    - name: Set up Android SDK
      uses: android-actions/setup-android@v2
      with:
        api-level: 34          # Change to your project's target API level
        build-tools: 34.0.2    # Change to your project's build tools version
        target: android-33
        ndk: 25.2.9519653      # Optional: Specify the NDK version if needed

    - name: Install dependencies
      run: ./gradlew dependencies

    - name: Run unit tests
      run: ./gradlew testDebugUnitTest
