name: Android CI Pipeline

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build-and-test:
    name: Build APK, AAB, and Run Unit Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Set up Android SDK
      uses: android-actions/setup-android@v2
      with:
        api-level: 34
        build-tools: 34.0.2
        target: android-33
        ndk: 25.2.9519653

    - name: Install dependencies
      run: ./gradlew dependencies

    - name: Run unit tests
      run: ./gradlew testDebugUnitTest

    - name: Build APK
      run: ./gradlew assembleDebug

    - name: Build AAB
      run: ./gradlew bundleRelease

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: debug-apk
        path: app/build/outputs/apk/debug/*.apk

    - name: Upload AAB
      uses: actions/upload-artifact@v3
      with:
        name: release-aab
        path: app/build/outputs/bundle/release/*.aab
